import { type NicheProfile, type SubNiche, type DesignDNA } from './types';

const defaultDNA: DesignDNA = {
  cardStyle: 'rounded', ctaStyle: 'pill', borderRadius: 16, spacingScale: 1.0,
  animationLevel: 'moderate', sectionGap: 80, heroHeight: '85vh', contentMaxWidth: 1100,
  imageStyle: 'gradient'
};

const luxuryDNA: DesignDNA = {
  cardStyle: 'sharp', ctaStyle: 'sharp', borderRadius: 0, spacingScale: 1.2,
  animationLevel: 'subtle', sectionGap: 120, heroHeight: '100vh', contentMaxWidth: 1200,
  imageStyle: 'pattern'
};

const techDNA: DesignDNA = {
  cardStyle: 'glass', ctaStyle: 'gradient', borderRadius: 12, spacingScale: 0.9,
  animationLevel: 'bold', sectionGap: 100, heroHeight: '90vh', contentMaxWidth: 1200,
  imageStyle: 'geometric'
};

const playfulDNA: DesignDNA = {
  cardStyle: 'bold', ctaStyle: 'pill', borderRadius: 24, spacingScale: 1.1,
  animationLevel: 'moderate', sectionGap: 80, heroHeight: '85vh', contentMaxWidth: 1100,
  imageStyle: 'emoji'
};

const minimalDNA: DesignDNA = {
  cardStyle: 'minimal', ctaStyle: 'minimal', borderRadius: 8, spacingScale: 1.3,
  animationLevel: 'none', sectionGap: 120, heroHeight: '80vh', contentMaxWidth: 900,
  imageStyle: 'gradient'
};

export const NICHE_PROFILES: Record<SubNiche, NicheProfile> = {
  // Ecommerce
  beauty_store: { subNiche: 'beauty_store', displayName: 'Beauty Store', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['✨','🌸','🌿','💄','🧴'], productLabel: 'Products', preferredHero: 'HeroStorefront', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['ProductCollections', 'BeautyRoutine', 'ProductFeatured', 'IngredientSpotlight'] },
  sneaker_store: { subNiche: 'sneaker_store', displayName: 'Sneaker Store', contentVoice: 'energetic', designDNA: techDNA, emojiSet: ['👟','🔥','⚡','🏃‍♂️','💨'], productLabel: 'Drops', preferredHero: 'HeroAthletic', preferredNav: 'NavbarSporty', preferredFooter: 'FooterEcommerce', sectionOrder: ['SneakerDrops', 'ProductGrid', 'FeaturesAlternating'] },
  gadget_store: { subNiche: 'gadget_store', displayName: 'Gadget Store', contentVoice: 'professional', designDNA: techDNA, emojiSet: ['📱','💻','⌚','🔋','🎧'], productLabel: 'Devices', preferredHero: 'HeroTech', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['ProductFeatured', 'SpecsComparison', 'FlashDeals'] },
  perfume_store: { subNiche: 'perfume_store', displayName: 'Perfume Store', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['✨','🌹','💎','🍾','🌙'], productLabel: 'Fragrances', preferredHero: 'HeroLuxury', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['FragranceNotes', 'ProductGrid', 'GiftingSection'] },
  furniture_store: { subNiche: 'furniture_store', displayName: 'Furniture Store', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['🛋️','🪑','🛏️','🪴','🏡'], productLabel: 'Pieces', preferredHero: 'HeroMinimalZen', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['RoomScenes', 'FurnitureCollections', 'ProductGrid'] },
  grocery_store: { subNiche: 'grocery_store', displayName: 'Grocery Store', contentVoice: 'warm', designDNA: playfulDNA, emojiSet: ['🍎','🥖','🥬','🥑','🛒'], productLabel: 'Items', preferredHero: 'HeroProduct', preferredNav: 'NavbarEcommerce', preferredFooter: 'FooterFull', sectionOrder: ['FreshCategories', 'DeliveryBanner', 'ProductGrid'] },
  jewelry_store: { subNiche: 'jewelry_store', displayName: 'Jewelry Store', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['💍','💎','✨','👑','🎁'], productLabel: 'Pieces', preferredHero: 'HeroLuxury', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['ProductFeatured', 'GalleryMasonry', 'TestimonialsQuote'] },
  pet_store: { subNiche: 'pet_store', displayName: 'Pet Store', contentVoice: 'playful', designDNA: playfulDNA, emojiSet: ['🐶','🐱','🦴','🐾','🎾'], productLabel: 'Supplies', preferredHero: 'HeroCenter', preferredNav: 'NavbarWarm', preferredFooter: 'FooterFull', sectionOrder: ['ProductCollections', 'ProductGrid', 'FAQAccordion'] },
  toy_store: { subNiche: 'toy_store', displayName: 'Toy Store', contentVoice: 'playful', designDNA: playfulDNA, emojiSet: ['🧸','🧩','🎈','🎨','🚀'], productLabel: 'Toys', preferredHero: 'HeroCenter', preferredNav: 'NavbarWarm', preferredFooter: 'FooterFull', sectionOrder: ['ProductCollections', 'ProductFeatured', 'FeaturesGrid'] },
  electronics_store: { subNiche: 'electronics_store', displayName: 'Electronics Store', contentVoice: 'professional', designDNA: techDNA, emojiSet: ['📺','🎮','🔌','🔊','📷'], productLabel: 'Electronics', preferredHero: 'HeroTech', preferredNav: 'NavbarDark', preferredFooter: 'FooterEcommerce', sectionOrder: ['FlashDeals', 'ProductGrid', 'SpecsComparison'] },
  organic_store: { subNiche: 'organic_store', displayName: 'Organic Store', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['🌱','🍏','🍯','🌿','🛒'], productLabel: 'Goods', preferredHero: 'HeroWarm', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['FreshCategories', 'ProductFeatured', 'TestimonialsGrid'] },
  fashion_luxury: { subNiche: 'fashion_luxury', displayName: 'Luxury Fashion', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['✨','👗','👠','👜','💎'], productLabel: 'Collection', preferredHero: 'HeroLuxury', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['ProductCollections', 'GalleryGrid', 'ProductFeatured'] },
  fashion_streetwear: { subNiche: 'fashion_streetwear', displayName: 'Streetwear', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['🔥','🧢','👕','🛹','🎱'], productLabel: 'Drops', preferredHero: 'HeroAthletic', preferredNav: 'NavbarSporty', preferredFooter: 'FooterEcommerce', sectionOrder: ['SneakerDrops', 'ProductGrid', 'GalleryMasonry'] },
  fashion_minimal: { subNiche: 'fashion_minimal', displayName: 'Minimal Fashion', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['🧥','👖','🤍','🧵','📐'], productLabel: 'Pieces', preferredHero: 'HeroMinimalZen', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['ProductFeatured', 'ProductGrid', 'FeaturesCompact'] },
  
  // Food & Hospitality
  restaurant_fine: { subNiche: 'restaurant_fine', displayName: 'Fine Dining', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['🍷','🍽️','✨','🕯️','🥩'], productLabel: 'Dishes', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterLuxury', sectionOrder: ['MenuCards', 'GalleryGrid', 'TestimonialsQuote'] },
  restaurant_casual: { subNiche: 'restaurant_casual', displayName: 'Casual Restaurant', contentVoice: 'warm', designDNA: defaultDNA, emojiSet: ['🍕','🍔','🌮','🥤','🍟'], productLabel: 'Items', preferredHero: 'HeroCenter', preferredNav: 'NavbarWarm', preferredFooter: 'FooterFull', sectionOrder: ['MenuGrid', 'TestimonialsGrid', 'ContactMap'] },
  cafe_coffee: { subNiche: 'cafe_coffee', displayName: 'Coffee Shop', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['☕','🥐','🪴','📖','🤎'], productLabel: 'Menu', preferredHero: 'HeroWarm', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['MenuCards', 'GalleryGrid', 'ContactSplit'] },
  bakery: { subNiche: 'bakery', displayName: 'Bakery', contentVoice: 'warm', designDNA: playfulDNA, emojiSet: ['🥖','🧁','🥨','🍰','🍞'], productLabel: 'Treats', preferredHero: 'HeroWarm', preferredNav: 'NavbarWarm', preferredFooter: 'FooterFull', sectionOrder: ['ProductFeatured', 'MenuGrid', 'TestimonialsGrid'] },
  food_delivery: { subNiche: 'food_delivery', displayName: 'Food Delivery', contentVoice: 'energetic', designDNA: playfulDNA, emojiSet: ['🛵','🍕','🥗','🥡','⚡'], productLabel: 'Meals', preferredHero: 'HeroSplit', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'MenuGrid', 'DeliveryBanner'] },
  hotel_booking: { subNiche: 'hotel_booking', displayName: 'Hotel', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['🏨','🛏️','🌴','✨','🏊‍♂️'], productLabel: 'Rooms', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterLuxury', sectionOrder: ['RoomScenes', 'FeaturesAlternating', 'GalleryMasonry'] },
  bar_lounge: { subNiche: 'bar_lounge', displayName: 'Bar & Lounge', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['🍸','🥃','🎵','🌙','✨'], productLabel: 'Drinks', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterMinimal', sectionOrder: ['MenuGrid', 'GalleryGrid', 'ContactMap'] },

  // Health & Wellness
  hospital_general: { subNiche: 'hospital_general', displayName: 'Hospital', contentVoice: 'clinical', designDNA: defaultDNA, emojiSet: ['🏥','🩺','👨‍⚕️','💊','❤️'], productLabel: 'Services', preferredHero: 'HeroEmergency', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['StatsBar', 'DepartmentGrid', 'DoctorCards'] },
  dental_clinic: { subNiche: 'dental_clinic', displayName: 'Dental Clinic', contentVoice: 'professional', designDNA: minimalDNA, emojiSet: ['🦷','✨','😁','🩺','🏥'], productLabel: 'Services', preferredHero: 'HeroCenter', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'TeamCards', 'TestimonialsSlider'] },
  mental_health: { subNiche: 'mental_health', displayName: 'Mental Health', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['🧠','🌱','☀️','🛋️','💙'], productLabel: 'Therapies', preferredHero: 'HeroWarm', preferredNav: 'NavbarWarm', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesAlternating', 'TeamMinimal', 'FAQAccordion'] },
  pharmacy: { subNiche: 'pharmacy', displayName: 'Pharmacy', contentVoice: 'clinical', designDNA: defaultDNA, emojiSet: ['💊','🧴','🏥','⚕️','📦'], productLabel: 'Products', preferredHero: 'HeroProduct', preferredNav: 'NavbarEcommerce', preferredFooter: 'FooterFull', sectionOrder: ['ProductGrid', 'FeaturesGrid', 'ContactSplit'] },
  gym_fitness: { subNiche: 'gym_fitness', displayName: 'Gym', contentVoice: 'energetic', designDNA: techDNA, emojiSet: ['🏋️','💪','🏃‍♂️','🔥','🥊'], productLabel: 'Classes', preferredHero: 'HeroAthletic', preferredNav: 'NavbarSporty', preferredFooter: 'FooterFull', sectionOrder: ['ClassSchedule', 'TeamCards', 'MembershipTiers'] },
  yoga_studio: { subNiche: 'yoga_studio', displayName: 'Yoga Studio', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['🧘‍♀️','🌿','✨','🤍','🌱'], productLabel: 'Classes', preferredHero: 'HeroMinimalZen', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['ClassSchedule', 'TeamMinimal', 'PricingSimple'] },
  spa_wellness: { subNiche: 'spa_wellness', displayName: 'Spa', contentVoice: 'luxury', designDNA: minimalDNA, emojiSet: ['🧖‍♀️','🌿','🌸','✨','🕯️'], productLabel: 'Treatments', preferredHero: 'HeroWarm', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterMinimal', sectionOrder: ['MenuGrid', 'GalleryGrid', 'AppointmentBooker'] },
  salon_beauty: { subNiche: 'salon_beauty', displayName: 'Beauty Salon', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['💇‍♀️','💅','✨','💄','🎀'], productLabel: 'Services', preferredHero: 'HeroStorefront', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'GalleryMasonry', 'AppointmentBooker'] },
  barber_shop: { subNiche: 'barber_shop', displayName: 'Barber Shop', contentVoice: 'bold', designDNA: defaultDNA, emojiSet: ['💈','✂️','🧔','🔥','🪒'], productLabel: 'Services', preferredHero: 'HeroCenter', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['MenuGrid', 'GalleryGrid', 'TeamCards'] },

  // Tech & SaaS
  ai_saas: { subNiche: 'ai_saas', displayName: 'AI SaaS', contentVoice: 'professional', designDNA: techDNA, emojiSet: ['✨','🤖','⚡','🧠','🚀'], productLabel: 'Features', preferredHero: 'HeroBento', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesBento', 'IntegrationGrid', 'PricingCards'] },
  productivity_saas: { subNiche: 'productivity_saas', displayName: 'Productivity SaaS', contentVoice: 'casual', designDNA: defaultDNA, emojiSet: ['✅','📈','⚡','📅','🚀'], productLabel: 'Tools', preferredHero: 'HeroDashboard', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesAlternating', 'TestimonialsGrid', 'PricingCards'] },
  dev_tools: { subNiche: 'dev_tools', displayName: 'Developer Tools', contentVoice: 'professional', designDNA: techDNA, emojiSet: ['💻','⚡','🔧','🚀','🔒'], productLabel: 'Features', preferredHero: 'HeroDashboard', preferredNav: 'NavbarDark', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesGrid', 'IntegrationGrid', 'PricingTable'] },
  crypto_platform: { subNiche: 'crypto_platform', displayName: 'Crypto Platform', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['₿','📈','🚀','🔒','💎'], productLabel: 'Features', preferredHero: 'HeroSplit', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['StatsBar', 'FeaturesBento', 'PricingCards'] },
  fintech_app: { subNiche: 'fintech_app', displayName: 'Fintech App', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['💳','📈','💰','🔒','🚀'], productLabel: 'Features', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['TrustLogos', 'FeaturesGrid', 'TestimonialsGrid'] },
  analytics_dashboard: { subNiche: 'analytics_dashboard', displayName: 'Analytics', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['📊','📈','⚡','🎯','💡'], productLabel: 'Metrics', preferredHero: 'HeroDashboard', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesAlternating', 'StatsBar', 'PricingTable'] },

  // Creative
  photographer: { subNiche: 'photographer', displayName: 'Photographer', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['📸','✨','🖤','🎞️','🤍'], productLabel: 'Shoots', preferredHero: 'HeroPersonal', preferredNav: 'NavbarFloating', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'FeaturesCompact', 'ContactForm'] },
  ui_designer: { subNiche: 'ui_designer', displayName: 'UI Designer', contentVoice: 'minimal', designDNA: techDNA, emojiSet: ['✨','🎨','💻','🚀','📱'], productLabel: 'Projects', preferredHero: 'HeroPersonal', preferredNav: 'NavbarCreator', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryGrid', 'TimelineSection', 'ContactSplit'] },
  illustrator: { subNiche: 'illustrator', displayName: 'Illustrator', contentVoice: 'playful', designDNA: playfulDNA, emojiSet: ['🎨','✏️','✨','🌈','🖼️'], productLabel: 'Works', preferredHero: 'HeroCenter', preferredNav: 'NavbarFloating', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'TestimonialsQuote', 'ContactForm'] },
  writer_author: { subNiche: 'writer_author', displayName: 'Writer', contentVoice: 'editorial', designDNA: minimalDNA, emojiSet: ['✍️','📖','✨','🖋️','📚'], productLabel: 'Books', preferredHero: 'HeroEditorial', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['BookFeatured', 'TimelineSection', 'ContactSplit'] },
  musician: { subNiche: 'musician', displayName: 'Musician', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['🎵','🎸','🎤','🎧','✨'], productLabel: 'Releases', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryGrid', 'TimelineSection', 'ContactMap'] },
  video_creator: { subNiche: 'video_creator', displayName: 'Video Creator', contentVoice: 'energetic', designDNA: playfulDNA, emojiSet: ['🎥','🎬','✨','🍿','📺'], productLabel: 'Videos', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'StatsBar', 'ContactForm'] },

  // Professional
  law_firm: { subNiche: 'law_firm', displayName: 'Law Firm', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['⚖️','🏛️','📝','🤝','🛡️'], productLabel: 'Practices', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['PracticeAreas', 'CaseResults', 'TeamCards'] },
  accounting_firm: { subNiche: 'accounting_firm', displayName: 'Accounting Firm', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['📊','💼','💰','📈','🤝'], productLabel: 'Services', preferredHero: 'HeroCenter', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'StatsBar', 'TeamMinimal'] },
  consulting: { subNiche: 'consulting', displayName: 'Consulting', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['💡','🤝','📈','🎯','🚀'], productLabel: 'Services', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesAlternating', 'TestimonialsGrid', 'ContactSplit'] },
  marketing_agency: { subNiche: 'marketing_agency', displayName: 'Marketing Agency', contentVoice: 'energetic', designDNA: playfulDNA, emojiSet: ['🚀','📈','🎯','💡','📣'], productLabel: 'Services', preferredHero: 'HeroCenter', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'GalleryGrid', 'TestimonialsSlider'] },
  design_agency: { subNiche: 'design_agency', displayName: 'Design Agency', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['✨','🎨','📐','🚀','💡'], productLabel: 'Projects', preferredHero: 'HeroCenter', preferredNav: 'NavbarFloating', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'FeaturesAlternating', 'TeamMinimal'] },
  real_estate_luxury: { subNiche: 'real_estate_luxury', displayName: 'Luxury Real Estate', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['✨','🏰','🔑','🥂','💎'], productLabel: 'Properties', preferredHero: 'HeroImmersive', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['PropertyCards', 'FeaturesAlternating', 'TestimonialsQuote'] },
  real_estate_rental: { subNiche: 'real_estate_rental', displayName: 'Real Estate Rentals', contentVoice: 'casual', designDNA: defaultDNA, emojiSet: ['🏠','🔑','🛋️','🏢','📍'], productLabel: 'Listings', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['PropertySearch', 'PropertyCards', 'FAQAccordion'] },

  // Ed & Community
  online_academy: { subNiche: 'online_academy', displayName: 'Online Academy', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['🎓','📚','💻','✨','🚀'], productLabel: 'Courses', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['CourseCards', 'FeaturesGrid', 'InstructorSpotlight'] },
  coaching_mentor: { subNiche: 'coaching_mentor', displayName: 'Coaching', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['🌱','🤝','✨','🎯','💡'], productLabel: 'Programs', preferredHero: 'HeroPersonal', preferredNav: 'NavbarWarm', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesAlternating', 'TestimonialsQuote', 'PricingCards'] },
  ngo_charity: { subNiche: 'ngo_charity', displayName: 'NGO', contentVoice: 'warm', designDNA: defaultDNA, emojiSet: ['❤️','🌍','🤝','🌱','🕊️'], productLabel: 'Programs', preferredHero: 'HeroCenter', preferredNav: 'NavbarWarm', preferredFooter: 'FooterFull', sectionOrder: ['StatsBar', 'FeaturesGrid', 'GalleryGrid'] },
  church_community: { subNiche: 'church_community', displayName: 'Church', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['⛪','🕊️','❤️','🙏','✨'], productLabel: 'Events', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'GalleryMasonry', 'ContactMap'] },

  // Entertainment
  gaming_site: { subNiche: 'gaming_site', displayName: 'Gaming Site', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['🎮','👾','⚔️','🔥','🚀'], productLabel: 'Games', preferredHero: 'HeroImmersive', preferredNav: 'NavbarDark', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryGrid', 'FeaturesBento', 'PricingCards'] },
  streaming_platform: { subNiche: 'streaming_platform', displayName: 'Streaming', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['📺','🍿','🎬','✨','🚀'], productLabel: 'Shows', preferredHero: 'HeroImmersive', preferredNav: 'NavbarDark', preferredFooter: 'FooterMinimal', sectionOrder: ['ProductCollections', 'ProductGrid', 'PricingCards'] },
  podcast_site: { subNiche: 'podcast_site', displayName: 'Podcast', contentVoice: 'casual', designDNA: playfulDNA, emojiSet: ['🎙️','🎧','✨','📻','💬'], productLabel: 'Episodes', preferredHero: 'HeroCenter', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesGrid', 'TestimonialsQuote', 'ContactForm'] },
  travel_adventure: { subNiche: 'travel_adventure', displayName: 'Adventure Travel', contentVoice: 'energetic', designDNA: playfulDNA, emojiSet: ['🏔️','⛺','🎒','🗺️','✈️'], productLabel: 'Trips', preferredHero: 'HeroImmersive', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterFull', sectionOrder: ['DestinationCards', 'FeaturesGrid', 'GalleryMasonry'] },
  travel_luxury: { subNiche: 'travel_luxury', displayName: 'Luxury Travel', contentVoice: 'luxury', designDNA: luxuryDNA, emojiSet: ['✈️','🌴','🥂','✨','🏨'], productLabel: 'Destinations', preferredHero: 'HeroImmersive', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterLuxury', sectionOrder: ['DestinationCards', 'RoomScenes', 'TestimonialsQuote'] },
  wedding_planner: { subNiche: 'wedding_planner', displayName: 'Wedding Planner', contentVoice: 'luxury', designDNA: minimalDNA, emojiSet: ['💍','💐','✨','🥂','🤍'], productLabel: 'Services', preferredHero: 'HeroWarm', preferredNav: 'NavbarLuxury', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'TestimonialsQuote', 'FeaturesGrid'] },
  event_corporate: { subNiche: 'event_corporate', displayName: 'Corporate Event', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['🎤','🤝','📊','✨','🏢'], productLabel: 'Events', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'GalleryGrid', 'PricingCards'] },

  // Advanced Clones / Stress Tests
  netflix_clone: { subNiche: 'netflix_clone', displayName: 'Netflix Clone', contentVoice: 'bold', designDNA: techDNA, emojiSet: ['🍿','🎬','📺','✨','🔥'], productLabel: 'Shows', preferredHero: 'HeroNetflix', preferredNav: 'NavbarDark', preferredFooter: 'FooterMinimal', sectionOrder: ['NetflixSliders', 'NetflixSliders', 'FAQAccordion'] },
  chatgpt_clone: { subNiche: 'chatgpt_clone', displayName: 'ChatGPT Clone', contentVoice: 'professional', designDNA: minimalDNA, emojiSet: ['🤖','✨','🧠','⚡','💡'], productLabel: 'Chats', preferredHero: 'HeroChatGPT', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['ChatGPTLayout'] },
  apple_style: { subNiche: 'apple_style', displayName: 'Apple Style', contentVoice: 'minimal', designDNA: minimalDNA, emojiSet: ['🍎','📱','💻','✨','🤍'], productLabel: 'Products', preferredHero: 'HeroApple', preferredNav: 'NavbarGlass', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesCompact', 'GalleryMasonry', 'ProductFeatured'] },
  cyberpunk: { subNiche: 'cyberpunk', displayName: 'Cyberpunk', contentVoice: 'energetic', designDNA: techDNA, emojiSet: ['👾','⚡','🔥','🦾','🔋'], productLabel: 'Tech', preferredHero: 'HeroCyberpunk', preferredNav: 'NavbarDark', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesBento', 'StatsBar', 'PricingCards'] },
  airbnb_clone: { subNiche: 'airbnb_clone', displayName: 'Airbnb Clone', contentVoice: 'warm', designDNA: defaultDNA, emojiSet: ['🏠','🌴','✈️','✨','📍'], productLabel: 'Homes', preferredHero: 'HeroAirbnb', preferredNav: 'NavbarFloating', preferredFooter: 'FooterMinimal', sectionOrder: ['AirbnbSearch', 'PropertyCards', 'GalleryGrid'] },
  amazon_clone: { subNiche: 'amazon_clone', displayName: 'Amazon Clone', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['📦','🛒','⚡','🔥','💰'], productLabel: 'Items', preferredHero: 'HeroAmazon', preferredNav: 'NavbarEcommerce', preferredFooter: 'FooterFull', sectionOrder: ['AmazonGrid', 'FlashDeals', 'ProductGrid'] },
  tesla_style: { subNiche: 'tesla_style', displayName: 'Tesla Style', contentVoice: 'minimal', designDNA: luxuryDNA, emojiSet: ['🚗','⚡','🔋','✨','🖤'], productLabel: 'Vehicles', preferredHero: 'HeroTesla', preferredNav: 'NavbarTransparent', preferredFooter: 'FooterMinimal', sectionOrder: ['TeslaSections', 'SpecsComparison'] },

  // Generic/Other
  startup_launch: { subNiche: 'startup_launch', displayName: 'Startup Launch', contentVoice: 'energetic', designDNA: techDNA, emojiSet: ['🚀','✨','⚡','💡','🎯'], productLabel: 'Features', preferredHero: 'HeroBento', preferredNav: 'NavbarFloating', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesBento', 'PricingCards', 'FAQAccordion'] },
  corporate_enterprise: { subNiche: 'corporate_enterprise', displayName: 'Enterprise', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['🏢','📊','🤝','🌍','🔒'], productLabel: 'Services', preferredHero: 'HeroSplit', preferredNav: 'NavbarEnterprise', preferredFooter: 'FooterFull', sectionOrder: ['TrustLogos', 'FeaturesAlternating', 'StatsBar'] },
  blog_tech: { subNiche: 'blog_tech', displayName: 'Tech Blog', contentVoice: 'professional', designDNA: techDNA, emojiSet: ['💻','⚡','🚀','📝','🔍'], productLabel: 'Articles', preferredHero: 'HeroEditorial', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['BlogGrid', 'FeaturesCompact', 'ContactForm'] },
  blog_lifestyle: { subNiche: 'blog_lifestyle', displayName: 'Lifestyle Blog', contentVoice: 'warm', designDNA: minimalDNA, emojiSet: ['✨','🌿','☕','🤍','📸'], productLabel: 'Posts', preferredHero: 'HeroWarm', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['GalleryMasonry', 'BlogGrid', 'TestimonialsQuote'] },
  news_magazine: { subNiche: 'news_magazine', displayName: 'Magazine', contentVoice: 'editorial', designDNA: minimalDNA, emojiSet: ['📰','📸','✨','🖊️','🌍'], productLabel: 'Articles', preferredHero: 'HeroEditorial', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterFull', sectionOrder: ['BlogFeatured', 'BlogGrid', 'FeaturesGrid'] },
  landing_page: { subNiche: 'landing_page', displayName: 'Landing Page', contentVoice: 'energetic', designDNA: defaultDNA, emojiSet: ['🚀','✨','🎯','⚡','💡'], productLabel: 'Features', preferredHero: 'HeroCenter', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterMinimal', sectionOrder: ['FeaturesGrid', 'PricingCards', 'FAQAccordion'] },
  saas_generic: { subNiche: 'saas_generic', displayName: 'SaaS', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['⚡','🔒','📈','🚀','💻'], productLabel: 'Features', preferredHero: 'HeroSplit', preferredNav: 'NavbarDark', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesBento', 'TestimonialsGrid', 'PricingTable'] },
  generic: { subNiche: 'generic', displayName: 'Website', contentVoice: 'professional', designDNA: defaultDNA, emojiSet: ['✨','🚀','🎯','💻','💡'], productLabel: 'Services', preferredHero: 'HeroSplit', preferredNav: 'NavbarMinimal', preferredFooter: 'FooterFull', sectionOrder: ['FeaturesGrid', 'TestimonialsGrid', 'PricingCards'] }
};
