import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { type SiteBlueprint } from '../engine/types';

export const exportProject = async (blueprint: SiteBlueprint) => {
  const zip = new JSZip();
  const name = blueprint.copy.brandName.toLowerCase().replace(/\s+/g, '-');

  zip.file('index.html', `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${blueprint.copy.brandName} — ${blueprint.copy.tagline}</title>
  <meta name="description" content="${blueprint.copy.heroSub}" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body style="margin:0;font-family:'Inter',sans-serif;background:${blueprint.colors.bg};color:${blueprint.colors.text}">
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>`);

  zip.file('src/main.tsx', `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nimport './index.css'\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)`);

  zip.file('src/App.tsx', `import { useState } from 'react';\nexport default function App() {\n  return (\n    <div style={{background:'${blueprint.colors.bg}',color:'${blueprint.colors.text}',minHeight:'100vh',fontFamily:'Inter,sans-serif'}}>\n      <nav style={{padding:'20px 40px',borderBottom:'1px solid ${blueprint.colors.border}',display:'flex',alignItems:'center',justifyContent:'space-between'}}>\n        <span style={{fontSize:22,fontWeight:900,color:'${blueprint.colors.primary}'}}>${blueprint.copy.brandName}</span>\n        <div style={{display:'flex',gap:24}}>${blueprint.copy.navLinks.map(l => `<a href="${l.href}" style={{color:'${blueprint.colors.muted}',textDecoration:'none',fontWeight:500}}>${l.label}</a>`).join('')}</div>\n        <button style={{background:'${blueprint.colors.primary}',color:'#fff',border:'none',borderRadius:50,padding:'10px 24px',fontWeight:700,cursor:'pointer'}}>${blueprint.copy.heroCTA}</button>\n      </nav>\n      <main style={{maxWidth:1100,margin:'0 auto',padding:'120px 24px',textAlign:'center'}}>\n        <h1 style={{fontSize:64,fontWeight:900,letterSpacing:'-2px',marginBottom:24,lineHeight:1.05}}>${blueprint.copy.heroHeadline}</h1>\n        <p style={{fontSize:20,color:'${blueprint.colors.muted}',marginBottom:48,lineHeight:1.6,maxWidth:600,margin:'0 auto 48px'}}>${blueprint.copy.heroSub}</p>\n        <button style={{background:'${blueprint.colors.primary}',color:'#fff',border:'none',borderRadius:50,padding:'16px 40px',fontWeight:800,fontSize:18,cursor:'pointer'}}>${blueprint.copy.heroCTA}</button>\n      </main>\n    </div>\n  );\n}`);

  zip.file('src/index.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;\nbody{font-family:'Inter',sans-serif;}`);
  zip.file('package.json', JSON.stringify({ name, version: '0.0.0', type: 'module', scripts: { dev: 'vite', build: 'tsc -b && vite build' }, dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' }, devDependencies: { '@vitejs/plugin-react': '^4.3.1', typescript: '^5.5.3', vite: '^5.4.1' } }, null, 2));
  zip.file('README.md', `# ${blueprint.copy.brandName}\n\nGenerated by PromptForge AI.\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${name}.zip`);
};
